spring:
  datasource:
    url: jdbc:mysql://localhost:3309/ecommerce_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # create, create-drop, validate, update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
    secret: xajplNSKnmmet4l8OL8g1zYBN4elj+Bt6INiYyf3N6N2kt5gFtBPP/QrcSc/N2GY
    expiration: 900000 # 15 phút (đơn vị ms)
    refresh-expiration: 1800000



server:
  port: 8080

